<a href="https://colab.research.google.com/github/AkhilKumar2703/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**NUMPY**

In [ ]:
import numpy as np

In [ ]:
a = np.array(list(range(10)))

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b =a+5

In [ ]:
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
a/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [ ]:
a*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
a.shape  #showing it contains 10 elements

(10,)

In [ ]:
a = a.reshape(-1,1)
a.shape

##array operations

In [ ]:
print(a)
print(b)
a+b

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[ 5  6  7  8  9 10 11 12 13 14]


array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a-b

array([[ -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13, -14],
       [ -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13],
       [ -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12],
       [ -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10],
       [  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9],
       [  1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8],
       [  2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
       [  3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6],
       [  4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5]])

In [ ]:
a*b

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

In [ ]:
a/b

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.4       , 0.33333333, 0.28571429, 0.25      , 0.22222222,
        0.2       , 0.18181818, 0.16666667, 0.15384615, 0.14285714],
       [0.6       , 0.5       , 0.42857143, 0.375     , 0.33333333,
        0.3       , 0.27272727, 0.25      , 0.23076923, 0.21428571],
       [0.8       , 0.66666667, 0.57142857, 0.5       , 0.44444444,
        0.4       , 0.36363636, 0.33333333, 0.30769231, 0.28571429],
       [1.        , 0.83333333, 0.71428571, 0.625     , 0.55555556,
        0.5       , 0.45454545, 0.41666667, 0.38461538, 0.35714286],
       [1.2       , 1.        , 0.85714286, 0.75      , 0.66666667,
        0.6       , 0.54545455, 0.5       , 0.46153846, 0.42857143],
       [1.4       , 1.16666667, 1.       

In [ ]:
d = np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])